toolbar:
  - formatselect | bold italic strikethrough forecolor backcolor | link image | alignleft aligncenter alignright alignjustify  | numlist bullist outdent indent  | removeformat
plugins:
  - print
  - preview
  - fullpage
  - searchreplace
  - autolink
  - directionality
  - visualblocks
  - visualchars
  - fullscreen
  - image
  - link
  - media
  - template
  - codesample
  - table
  - charmap
  - hr
  - pagebreak
  - nonbreaking
  - anchor
  - toc
  - insertdatetime
  - advlist
  - lists
  - textcolor
  - wordcount
  - imagetools
  - contextmenu
  - colorpicker
  - textpattern
  - help